--- Makefile	2018-10-08 08:21:49.987871964 -0400
+++ Makefile_new	2018-10-08 08:22:51.598758453 -0400
@@ -10,7 +10,7 @@
 OPENFST_VERSION ?= 1.6.7
 
 # Default features configured for OpenFST; can be overridden in the make command line.
-OPENFST_CONFIGURE ?= --enable-static --enable-shared --enable-far --enable-ngram-fsts
+OPENFST_CONFIGURE ?= --enable-static --enable-shared --enable-far --enable-pdt --enable-mpdt --enable-grm --enable-ngram-fsts
 
 OPENFST_VER_NUM := $(shell echo $(OPENFST_VERSION) | sed 's/\./ /g' | xargs printf "%d%02d%02d")
 ifeq ("$(shell expr $(OPENFST_VER_NUM) \< 10600)","1")
